=== ErikaEspejo/erika-webpage/xsd/facturacion.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="facturas">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="factura" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="factura">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="numeroFactura" type="xs:string"/>
        <xs:element name="fecha" type="xs:date"/>
        <xs:element name="timestamp" type="xs:time"/>
        <xs:element name="estado" type="xs:string"/>
        <xs:element name="identificacionCliente" type="xs:string"/>
        <xs:element name="nombreCliente" type="xs:string"/>
        <xs:element name="direccionCliente" type="xs:string"/>
        <xs:element name="telefonoCliente" type="xs:string"/>
        <xs:element name="cuotas">
           <xs:simpleType>
              <xs:restriction base="xs:integer">
                 <xs:minInclusive value="1"/>
                 <xs:maxInclusive value="12"/>
              </xs:restriction>
           </xs:simpleType>
        </xs:element>
        <xs:element ref="detalles"/>
        <xs:element ref="pagos"/>
      </xs:sequence>
      <xs:attribute name="id" type="xs:integer" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="detalles">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="servicio" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="servicio">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="descripcion" type="xs:string"/>
        <xs:element name="cantidad" type="xs:integer"/>
        <xs:element name="valorUnitario" type="xs:decimal"/>
        <xs:element name="descuento" type="xs:decimal"/>
        <xs:element name="impuesto" type="xs:decimal"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="pagos">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="pago"  minOccurs="1" maxOccurs="12"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="pago">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="idPago" type="xs:string"/>
        <xs:element name="metodoPago" type="xs:string"/>
        <xs:element name="estadoPago" type="xs:string"/>
        <xs:element name="fechaPago" type="xs:date"/>
        <xs:element name="valorPago" type="xs:decimal"/>
        <xs:element name="numeroCuota" type="xs:integer"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== ErikaEspejo/erika-webpage/xml/facturacion.xml
<?xml version="1.0" encoding="UTF-8"?>
<facturas xmlns:fac="http://www.w3.org/2001/XMLSchema-instance" fac:noNamespaceSchemaLocation="../xsd/facturacion.xsd">
  <factura id="1">
    <numeroFactura>F001</numeroFactura>
    <fecha>2026-08-10</fecha>
    <timestamp>10:20:35</timestamp>
    <estado>pagada</estado>
    <identificacionCliente>123456789</identificacionCliente>
    <nombreCliente>Pepito Pérez</nombreCliente>
    <direccionCliente>Calle Siempre Viva #123</direccionCliente>
    <telefonoCliente>55526658</telefonoCliente>
    <cuotas>1</cuotas>
    <detalles>
      <servicio>
        <descripcion>Consultoría n8n</descripcion>
        <cantidad>1</cantidad>
        <valorUnitario>1000000</valorUnitario>
        <descuento>0</descuento>
        <impuesto>100000</impuesto>
      </servicio>
    </detalles>
    <pagos>
      <pago>
        <idPago>1</idPago>
        <metodoPago>Tarjeta de Credito</metodoPago>
        <estadoPago>pagado</estadoPago>
        <fechaPago>2026-08-10</fechaPago>
        <valorPago>1100000</valorPago>
        <numeroCuota>1</numeroCuota>
      </pago>
    </pagos>
  </factura>
  <factura id="2">
    <numeroFactura>F002</numeroFactura>
    <fecha>2026-08-11</fecha>
    <timestamp>10:20:35</timestamp>
    <estado>pagada</estado>
    <identificacionCliente>123456489</identificacionCliente>
    <nombreCliente>Pepito Pérez</nombreCliente>
    <direccionCliente>Calle Siempre Viva #123</direccionCliente>
    <telefonoCliente>55526658</telefonoCliente>
    <cuotas>1</cuotas>
    <detalles>
      <servicio>
        <descripcion>Consultoría n8n</descripcion>
        <cantidad>1</cantidad>
        <valorUnitario>1000000</valorUnitario>
        <descuento>0</descuento>
        <impuesto>100000</impuesto>
      </servicio>
    </detalles>
    <pagos>
      <pago>
        <idPago>1</idPago>
        <metodoPago>Tarjeta de Credito</metodoPago>
        <estadoPago>pagado</estadoPago>
        <fechaPago>2026-08-10</fechaPago>
        <valorPago>1100000</valorPago>
        <numeroCuota>1</numeroCuota>
      </pago>
    </pagos>
  </factura>
  <factura id="3">
    <numeroFactura>F002</numeroFactura>
    <fecha>2026-08-11</fecha>
    <timestamp>10:20:35</timestamp>
    <estado>pagada</estado>
    <identificacionCliente>123456489</identificacionCliente>
    <nombreCliente>Pepito Pérez</nombreCliente>
    <direccionCliente>Calle Siempre Viva #123</direccionCliente>
    <telefonoCliente>55526658</telefonoCliente>
    <cuotas>1</cuotas>
    <detalles>
      <servicio>
        <descripcion>Consultoría n8n</descripcion>
        <cantidad>1</cantidad>
        <valorUnitario>1000000</valorUnitario>
        <descuento>0</descuento>
        <impuesto>100000</impuesto>
      </servicio>
    </detalles>
    <pagos>
      <pago>
        <idPago>1</idPago>
        <metodoPago>Tarjeta de Credito</metodoPago>
        <estadoPago>pagado</estadoPago>
        <fechaPago>2026-08-10</fechaPago>
        <valorPago>1100000</valorPago>
        <numeroCuota>1</numeroCuota>
      </pago>
    </pagos>
  </factura>
  <factura id="4">
    <numeroFactura>F002</numeroFactura>
    <fecha>2026-08-11</fecha>
    <timestamp>10:20:35</timestamp>
    <estado>pagada</estado>
    <identificacionCliente>123456489</identificacionCliente>
    <nombreCliente>Pepito Pérez</nombreCliente>
    <direccionCliente>Calle Siempre Viva #123</direccionCliente>
    <telefonoCliente>55526658</telefonoCliente>
    <cuotas>1</cuotas>
    <detalles>
      <servicio>
        <descripcion>Consultoría n8n</descripcion>
        <cantidad>1</cantidad>
        <valorUnitario>1000000</valorUnitario>
        <descuento>0</descuento>
        <impuesto>100000</impuesto>
      </servicio>
    </detalles>
    <pagos>
      <pago>
        <idPago>1</idPago>
        <metodoPago>Tarjeta de Credito</metodoPago>
        <estadoPago>pagado</estadoPago>
        <fechaPago>2026-08-10</fechaPago>
        <valorPago>1100000</valorPago>
        <numeroCuota>1</numeroCuota>
      </pago>
    </pagos>
  </factura>
  <factura id="5">
    <numeroFactura>F002</numeroFactura>
    <fecha>2026-08-11</fecha>
    <timestamp>10:20:35</timestamp>
    <estado>pagada</estado>
    <identificacionCliente>123456489</identificacionCliente>
    <nombreCliente>Pepito Pérez</nombreCliente>
    <direccionCliente>Calle Siempre Viva #123</direccionCliente>
    <telefonoCliente>55526658</telefonoCliente>
    <cuotas>1</cuotas>
    <detalles>
      <servicio>
        <descripcion>Consultoría n8n</descripcion>
        <cantidad>1</cantidad>
        <valorUnitario>1000000</valorUnitario>
        <descuento>0</descuento>
        <impuesto>100000</impuesto>
      </servicio>
    </detalles>
    <pagos>
      <pago>
        <idPago>1</idPago>
        <metodoPago>Tarjeta de Credito</metodoPago>
        <estadoPago>pagado</estadoPago>
        <fechaPago>2026-08-10</fechaPago>
        <valorPago>1100000</valorPago>
        <numeroCuota>1</numeroCuota>
      </pago>
    </pagos>
  </factura>
  <factura id="6">
    <numeroFactura>F002</numeroFactura>
    <fecha>2026-08-11</fecha>
    <timestamp>10:20:35</timestamp>
    <estado>pagada</estado>
    <identificacionCliente>123456489</identificacionCliente>
    <nombreCliente>Pepito Pérez</nombreCliente>
    <direccionCliente>Calle Siempre Viva #123</direccionCliente>
    <telefonoCliente>55526658</telefonoCliente>
    <cuotas>1</cuotas>
    <detalles>
      <servicio>
        <descripcion>Consultoría n8n</descripcion>
        <cantidad>1</cantidad>
        <valorUnitario>1000000</valorUnitario>
        <descuento>0</descuento>
        <impuesto>100000</impuesto>
      </servicio>
    </detalles>
    <pagos>
      <pago>
        <idPago>1</idPago>
        <metodoPago>Tarjeta de Credito</metodoPago>
        <estadoPago>pagado</estadoPago>
        <fechaPago>2026-08-10</fechaPago>
        <valorPago>1100000</valorPago>
        <numeroCuota>1</numeroCuota>
      </pago>
    </pagos>
  </factura>
  <factura id="7">
    <numeroFactura>F002</numeroFactura>
    <fecha>2026-08-11</fecha>
    <timestamp>10:20:35</timestamp>
    <estado>pagada</estado>
    <identificacionCliente>123456489</identificacionCliente>
    <nombreCliente>Pepito Pérez</nombreCliente>
    <direccionCliente>Calle Siempre Viva #123</direccionCliente>
    <telefonoCliente>55526658</telefonoCliente>
    <cuotas>1</cuotas>
    <detalles>
      <servicio>
        <descripcion>Consultoría n8n</descripcion>
        <cantidad>1</cantidad>
        <valorUnitario>1000000</valorUnitario>
        <descuento>0</descuento>
        <impuesto>100000</impuesto>
      </servicio>
    </detalles>
    <pagos>
      <pago>
        <idPago>1</idPago>
        <metodoPago>Tarjeta de Credito</metodoPago>
        <estadoPago>pagado</estadoPago>
        <fechaPago>2026-08-10</fechaPago>
        <valorPago>1100000</valorPago>
        <numeroCuota>1</numeroCuota>
      </pago>
    </pagos>
  </factura>
  <factura id="8">
    <numeroFactura>F002</numeroFactura>
    <fecha>2026-08-11</fecha>
    <timestamp>10:20:35</timestamp>
    <estado>pagada</estado>
    <identificacionCliente>123456489</identificacionCliente>
    <nombreCliente>Pepito Pérez</nombreCliente>
    <direccionCliente>Calle Siempre Viva #123</direccionCliente>
    <telefonoCliente>55526658</telefonoCliente>
    <cuotas>1</cuotas>
    <detalles>
      <servicio>
        <descripcion>Consultoría n8n</descripcion>
        <cantidad>1</cantidad>
        <valorUnitario>1000000</valorUnitario>
        <descuento>0</descuento>
        <impuesto>100000</impuesto>
      </servicio>
    </detalles>
    <pagos>
      <pago>
        <idPago>1</idPago>
        <metodoPago>Tarjeta de Credito</metodoPago>
        <estadoPago>pagado</estadoPago>
        <fechaPago>2026-08-10</fechaPago>
        <valorPago>1100000</valorPago>
        <numeroCuota>1</numeroCuota>
      </pago>
    </pagos>
  </factura>
  <factura id="9">
    <numeroFactura>F002</numeroFactura>
    <fecha>2026-08-11</fecha>
    <timestamp>10:20:35</timestamp>
    <estado>pagada</estado>
    <identificacionCliente>123456489</identificacionCliente>
    <nombreCliente>Pepito Pérez</nombreCliente>
    <direccionCliente>Calle Siempre Viva #123</direccionCliente>
    <telefonoCliente>55526658</telefonoCliente>
    <cuotas>1</cuotas>
    <detalles>
      <servicio>
        <descripcion>Consultoría n8n</descripcion>
        <cantidad>1</cantidad>
        <valorUnitario>1000000</valorUnitario>
        <descuento>0</descuento>
        <impuesto>100000</impuesto>
      </servicio>
    </detalles>
    <pagos>
      <pago>
        <idPago>1</idPago>
        <metodoPago>Tarjeta de Credito</metodoPago>
        <estadoPago>pagado</estadoPago>
        <fechaPago>2026-08-10</fechaPago>
        <valorPago>1100000</valorPago>
        <numeroCuota>1</numeroCuota>
      </pago>
    </pagos>
  </factura>
  <factura id="10">
    <numeroFactura>F002</numeroFactura>
    <fecha>2026-08-11</fecha>
    <timestamp>10:20:35</timestamp>
    <estado>pagada</estado>
    <identificacionCliente>123456489</identificacionCliente>
    <nombreCliente>Pepito Pérez</nombreCliente>
    <direccionCliente>Calle Siempre Viva #123</direccionCliente>
    <telefonoCliente>55526658</telefonoCliente>
    <cuotas>1</cuotas>
    <detalles>
      <servicio>
        <descripcion>Consultoría n8n</descripcion>
        <cantidad>1</cantidad>
        <valorUnitario>1000000</valorUnitario>
        <descuento>0</descuento>
        <impuesto>100000</impuesto>
      </servicio>
    </detalles>
    <pagos>
      <pago>
        <idPago>1</idPago>
        <metodoPago>Tarjeta de Credito</metodoPago>
        <estadoPago>pagado</estadoPago>
        <fechaPago>2026-08-10</fechaPago>
        <valorPago>1100000</valorPago>
        <numeroCuota>1</numeroCuota>
      </pago>
    </pagos>
  </factura>
</facturas>
